### ISSUE TITLE
[Wiki] Multi-bot docker configuration

### ISSUE THREAD

**Issue by nia-aio** [PokemonGoF/PokemonGo-Bot#3492]
Thought I'd contribute how I'm now running the bot for multiple accounts using docker + compose.

## Multiple containers with docker-compose
(Ubuntu 16.04, possibly Ubuntu 14.04 if you change xenial to trusty)
Install git, Docker, Docker-Compose(assuming root for all steps)
```
apt-get -y update
apt-get -y install apt-transport-https ca-certificates curl vim git
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list

apt-get -y update
apt-get -y install linux-image-extra-$(uname -r)
apt-get -y install docker-engine
echo 'DOCKER_OPTS="--dns 8.8.8.8"' >> /etc/default/docker

curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose

service docker start
systemctl enable docker
```

Download relevant projects, since I dedicated a VM for this, they're in /root for me
```
git clone --branch dev https://github.com/PokemonGoF/PokemonGo-Bot.git /root/PokemonGo-Bot
cd /root/PokemonGo-Bot
git submodule init
git submodule update
```

Keep configs seperate, this will help keep the containers neutral and make them only rebuild when the bot has changed
```
mkdir /root/configs /root/data
cp /root/PokemonGo-Bot/configs/* /root/configs/
cp /root/PokemonGo-Bot/web/config/userdata.js.example /root/configs/userdata.js
```

Now create the universal docker-compose file, `vim /root/docker-compose.yml` (Can also be created locally and uploaded via Filezilla, you only need to change `botX:` and `configs/botX.json`)
```
version: '2'
services:
  bot1: &BOTDEFAULT
    build: ./PokemonGo-Bot
    volumes:
      - ./PokemonGo-Bot/web:/usr/src/app/web
      - ./configs:/usr/src/app/configs
      - ./data:/usr/src/app/data
    stdin_open: true
    tty: true
    command: --config configs/bot1.json
  bot2:
    <<: *BOTDEFAULT
    command: --config configs/bot2.json
  bot3:
    <<: *BOTDEFAULT
    command: --config configs/bot3.json
  bot-webview:
    image: nginx:1.11.1
    ports:
      - "8000:80"
    volumes:
      - ./PokemonGo-Bot/web:/usr/share/nginx/html
      - ./configs/userdata.js:/usr/share/nginx/html/config/userdata.js
```

yml files used spaces instead of tabs and can be really sensitive to typos.
Nginx handles being bashed by requests far better than python's SimpleHTTPServer, and generally takes far less resources.

To control the containers now(Must be in the same directory as the `docker-compose.yml` file):
* `docker-compose build` Builds all necessary containers
* `docker-compose up -d ` Builds the containers and starts them all in the background, also restarts them automatically if the container was rebuilt or the config file was changed
* `docker-compose logs` Spits out all the container's output
* `docker-compose logs -f ` Constantly outputs all container's command line outputs
* `docker-compose restart` Restart all containers
* `docker-compose restart [botX]` Restarts a specific bot/container
* `docker-compose stop` Stops all containers
* `docker-compose stop [botX]` Stops a specific bot/container. In the sample yml file, this would be bot1,bot2,bot3, or bot-webview
* `docker-compose rm` Deletes all container(doesn't delete container image, or data in the volumes directories)
* `docker-compose rm [botX]` Deletes specific container(doesn't delete container image, or data in the volumes directories)

*edit*
If new to all this, keep all config json files within `/root/configs`. Don't forget to configure `/root/configs/userdata.js` for the web interface.
For my own sanity, I keep all my path files in `/root/configs/paths/` as this directory will also be included into the docker container on startup.
